### ISSUE TITLE
cannot properly average multiple T1s and T2s when running preBIBSnet

### ISSUE THREAD

**Issue by lundq163** [DCAN-Labs/BIBSnet#24]
### What happened?

when there are multiple T1s and/or T2s, it writes the `flirt.mat` file for averaging out to the top level directory instead of under preBIBSnet. Then later has trouble finding that `.mat` file 

### What command did you use?

```shell
${singularity} run --nv --cleanenv --no-home \
> -B ${data_dir}:/input \
> -B ${data_dir}/processed/cabinet:/output \
> -B ${run_dir}/license.txt:/opt/freesurfer/license.txt \
> /home/faird/shared/code/internal/pipelines/cabinet_container/cabinet_latest.sif \
> /input /output participant -jargs /home/cabinet/parameter-file-container.json -start prebibsnet -end postbibsnet -v
```

### What version of CABINET are you using?

the latest version of CABINET (11-15-2022)

### Relevant log output

```shell
"uname": executable file not found in $PATH

INFO 2023-01-06 13:58:18,264: Subject details from participants.tsv row:
  participant_id       session age
0      sub-M1003  ses-20191205   1

INFO 2023-01-06 13:58:18,267: Subject age in months: 1
Closest BCP age in months in age-to-head-radius table: 1

INFO 2023-01-06 13:58:18,315: /home/cabinet/cabinet /input /output participant -jargs /home/cabinet/parameter-file-container.json -start prebibsnet -end postbibsnet -v

INFO 2023-01-06 13:58:18,315: All parameters from input args and input .JSON file:
{'common': {'fsl_bin_path': '/opt/fsl-6.0.5.1/bin/', 'task_id': None, 'bids_dir': '/input', 'overwrite': False, 'verbose': True}, 'resource_management': {'mem_mb': None, 'n_cpus': None, 'nipype_plugin_file': None, 'nthreads': None, 'omp_nthreads': None, 'resource_monitor': None}, 'bibsnet': {'model': '3d_fullres', 'nnUNet_predict_path': '/opt/conda/bin/nnUNet_predict', 'code_dir': '/home/cabinet/SW/BIBSnet'}, 'meta': {'script_dir': '/home/cabinet', 'slurm': False}, 'stage_names': {'start': 'prebibsnet', 'end': 'postbibsnet'}, 'optional_out_dirs': {'prebibsnet': '/output/prebibsnet', 'bibsnet': '/output/bibsnet', 'postbibsnet': '/output/postbibsnet', 'nibabies': '/output/nibabies', 'xcpd': '/output/xcpd', 'derivatives': '/output'}}

INFO 2023-01-06 13:58:18,315: All required input files exist.

INFO 2023-01-06 13:58:18,315: Now running prebibsnet stage on:
{'subject': 'sub-M1003', 'session': 'ses-20191205', 'age_months': 1, 'brain_z_size': 119, 'has_T1w': True, 'has_T2w': True, 'model': 512}
230106-13:58:19,80 nipype.utils WARNING:
	 A newer version (1.8.4) of nipy/nipype is available. You are using 1.7.0

WARNING 2023-01-06 13:58:19,080: A newer version (1.8.4) of nipy/nipype is available. You are using 1.7.0
flirt -in /input/sub-M1003/ses-20191205/anat/sub-M1003_ses-20191205_run-02_T2w.nii.gz -ref /input/sub-M1003/ses-20191205/anat/sub-M1003_ses-20191205_run-01_T2w.nii.gz -out sub-M1003_ses-20191205_run-02_T2w_flirt.nii.gz -omat sub-M1003_ses-20191205_run-02_T2w_flirt.mat -bins 640 -searchcost mutualinfo
230106-14:10:13,88 nipype.interface INFO:
	 stderr 2023-01-06T14:10:13.087741:Could not open file sub-M1003_ses-20191205_run-02_T2w_flirt.mat for writing

INFO 2023-01-06 14:10:13,088: stderr 2023-01-06T14:10:13.087741:Could not open file sub-M1003_ses-20191205_run-02_T2w_flirt.mat for writing
230106-14:10:15,100 nipype.interface INFO:
	 stderr 2023-01-06T14:10:15.100832:Error: cant open file sub-M1003_ses-20191205_run-02_T2w_flirt.nii.gz

INFO 2023-01-06 14:10:15,100: stderr 2023-01-06T14:10:15.100832:Error: cant open file sub-M1003_ses-20191205_run-02_T2w_flirt.nii.gz
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 454, in aggregate_outputs
    setattr(outputs, key, val)
  File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/traits_extension.py", line 330, in validate
    value = super(File, self).validate(objekt, name, value, return_pathlike=True)
  File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/traits_extension.py", line 135, in validate
    self.error(objekt, name, str(value))
  File "/opt/conda/lib/python3.8/site-packages/traits/base_trait_handler.py", line 74, in error
    raise TraitError(
traits.trait_errors.TraitError: The 'out_matrix_file' trait of a FLIRTOutputSpec instance must be a pathlike object or string representing an existing file, but a value of '/sub-M1003_ses-20191205_run-02_T2w_flirt.mat' <class 'str'> was specified.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cabinet/cabinet", line 1002, in <module>
    main()
  File "/home/cabinet/cabinet", line 76, in main
    run_all_stages(STAGES, sub_ses_IDs, json_args["stage_names"]["start"],
  File "/home/cabinet/src/utilities.py", line 1260, in run_all_stages
    sub_ses_j_args = stage(sub_ses_j_args, logger)
  File "/home/cabinet/cabinet", line 528, in run_preBIBSnet
    create_anatomical_average(preBIBSnet_paths["avg"])  # TODO make averaging optional with later BIBSnet model?
  File "/home/cabinet/src/utilities.py", line 426, in create_anatomical_average
    register_and_average_files(avg_params["T{}w_input".format(t)],
  File "/home/cabinet/src/utilities.py", line 1052, in register_and_average_files
    registered_files = register_files(input_file_paths, reference)
  File "/home/cabinet/src/utilities.py", line 1072, in register_files
    res = flt.run()
  File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 401, in run
    outputs = self.aggregate_outputs(runtime)
  File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/fsl/preprocess.py", line 742, in aggregate_outputs
    outputs = super(FLIRT, self).aggregate_outputs(
  File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 461, in aggregate_outputs
    raise FileNotFoundError(msg)
FileNotFoundError: No such file or directory '/sub-M1003_ses-20191205_run-02_T2w_flirt.mat' for output 'out_matrix_file' of a FLIRT interface
```

### Add any additional information or context about the problem here.

problem occurred when running an s3 wrapper but was later reproduced in the terminal interactively via an srun

**Comment by LuciMoore** [comment]
resolved in prior versions
