### ISSUE TITLE
Issues copying concatenated .mat file from pre to post bibsnet when multiple sessions are included for one subject

### ISSUE THREAD

**Issue by audreymhoughton** [DCAN-Labs/BIBSnet#29]
### What happened?

Issues copying concatenated .mat file from pre to post bibsnet when it's t2-only - results in an exit code 1, because it can't complete postbibsnet

### What command did you use?

```shell
current cabinet singularity run command
```

### What version of CABINET are you using?

old container, working_dir branch bound (soon to be merged into main)

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/cabinet/cabinet", line 1014, in <module>
    main()
  File "/home/cabinet/cabinet", line 76, in main
    run_all_stages(STAGES, sub_ses_IDs, json_args["stage_names"]["start"],
  File "/home/cabinet/src/utilities.py", line 1331, in run_all_stages
    sub_ses_j_args = stage(sub_ses_j_args, logger)
  File "/home/cabinet/cabinet", line 648, in run_preBIBSnet
    shutil.copy2(concat_mat, out_mat_fpath)
  File "/opt/conda/lib/python3.8/shutil.py", line 435, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/opt/conda/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/cabinet/postbibsnet/sub-CENSORED/ses-10mo/preBIBSnet_full_crop_T2w_to_BIBS_template.mat'
```

**Comment by rosemccollum** [comment]
a work_dir needs to be specified for it to work on multiple sessions.

**Comment by LuciMoore** [comment]
This is the error I'm seeing:
```

Traceback (most recent call last):
  File "/home/cabinet/cabinet", line 519, in read_from_tsv
    desired_output = get_col_value_from_tsv(j_args, logger, tsv_path, ID_col, col_name, sub_ses)
  File "/home/cabinet/cabinet", line 539, in get_col_value_from_tsv
    tsv_df = pd.read_csv(
  File "/opt/conda/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/opt/conda/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 488, in _read
    return parser.read(nrows)
  File "/opt/conda/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1047, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/opt/conda/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 310, in read
    index, names = self._make_index(data, alldata, names)
  File "/opt/conda/lib/python3.8/site-packages/pandas/io/parsers/base_parser.py", line 415, in _make_index
    index = self._get_simple_index(alldata, columns)
  File "/opt/conda/lib/python3.8/site-packages/pandas/io/parsers/base_parser.py", line 447, in _get_simple_index
    i = ix(idx)
  File "/opt/conda/lib/python3.8/site-packages/pandas/io/parsers/base_parser.py", line 442, in ix
    raise ValueError(f"Index {col} invalid")
ValueError: Index session invalid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cabinet/cabinet", line 1044, in <module>
    main()
  File "/home/cabinet/cabinet", line 69, in main
    json_args, sub_ses_IDs = get_params_from_JSON([get_stage_name(stg) for stg
  File "/home/cabinet/cabinet", line 211, in get_params_from_JSON
    return validate_cli_args(vars(parser.parse_args()), stage_names,
  File "/home/cabinet/cabinet", line 289, in validate_cli_args
    sub_ses_IDs[ix]["age_months"] = read_from_tsv(
  File "/home/cabinet/cabinet", line 529, in read_from_tsv
    desired_output = get_col_value_from_tsv(j_args, logger, tsv_path, ID_col, col_name, sub_ses)
  File "/home/cabinet/cabinet", line 557, in get_col_value_from_tsv
    return int(subj_row[col_name])
  File "/opt/conda/lib/python3.8/site-packages/pandas/core/series.py", line 185, in wrapper
    raise TypeError(f"cannot convert the series to {converter}")
TypeError: cannot convert the series to <class 'int'>

```

@rosemccollum can you confirm that you got this same error?

**Comment by tjhendrickson** [comment]
Any updates on this item @rosemccollum?

**Comment by rosemccollum** [comment]
As far as I'm aware, this is still an issue. @tikal004 tried a fix a while ago but I was still unable to get it to successfully process multiple sessions at a time. I still got the FileNotFoundError Audrey mentioned in the original issue.

**Comment by tikal004** [comment]
It's probably worth me taking another look as its been a bit and I understand the codebase more now. @rosemccollum I might reach out for details
